### ISSUE TITLE
Watch task not detecting newly added files

### ISSUE THREAD

**Issue by boye** [e-sites/gulp-frontend-tasks#1]
We should investigate if this is a restriction within `gulp.watch`...or if there might be a way to work around it

**Comment by iainvdw** [comment]
Been there, done that, got the t-shirt ;)

This is a restricition of the watch module within gulp. This is going to be refactored in gulp 4.x, which contains a new/updated watcher module that should solve these problems. It's a known issue, see gulpjs/gulp#651.

Sorry :(
